// <auto-generated />
using System;
using LagFinanceLib.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LagFinanceLib.Migrations
{
    [DbContext(typeof(LagFinanceDbContext))]
    partial class LagFinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LagFinanceLib.Domain.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categoria", "finance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f7cce04-9ec5-4f43-bfdb-4ed1e478f1d4"),
                            Descricao = "Mercado"
                        },
                        new
                        {
                            Id = new Guid("21bf5615-c004-4a31-99f8-b376afc573bc"),
                            Descricao = "Contas"
                        },
                        new
                        {
                            Id = new Guid("88c747e2-45ad-4067-aab8-ab287ceed954"),
                            Descricao = "Farmacia"
                        },
                        new
                        {
                            Id = new Guid("42c74818-8ef2-45b9-9ab6-a7dcd6dcc36f"),
                            Descricao = "Lazer"
                        },
                        new
                        {
                            Id = new Guid("cf668fda-3d80-47c6-8352-6c04fb28c956"),
                            Descricao = "Restaurante"
                        });
                });

            modelBuilder.Entity("LagFinanceLib.Domain.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conta", "finance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ab68e5a-a829-40b9-9d32-b9746d3134f5"),
                            Descricao = "Bradesco"
                        },
                        new
                        {
                            Id = new Guid("60b44dcc-950e-45b1-bbb2-32c5deb9ec90"),
                            Descricao = "Banco do Brasil"
                        },
                        new
                        {
                            Id = new Guid("64abc81e-dd01-40b8-983a-3dba10cfb7ab"),
                            Descricao = "Santander"
                        },
                        new
                        {
                            Id = new Guid("0ca05b72-4e7d-4afe-8bc9-c0b8cc860073"),
                            Descricao = "PicPay"
                        });
                });

            modelBuilder.Entity("LagFinanceLib.Domain.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContaTransferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pendente")
                        .HasColumnType("bit");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("ContaTransferenciaId");

                    b.ToTable("Movimentacao", "finance");
                });

            modelBuilder.Entity("LagFinanceLib.Domain.Movimentacao", b =>
                {
                    b.HasOne("LagFinanceLib.Domain.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagFinanceLib.Domain.Conta", "Conta")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagFinanceLib.Domain.Conta", "ContaTransferencia")
                        .WithMany()
                        .HasForeignKey("ContaTransferenciaId");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("ContaTransferencia");
                });

            modelBuilder.Entity("LagFinanceLib.Domain.Conta", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
