<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>a9d97c28-a4a1-4eb2-aee8-0f274ca0bc37</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.Development.json" />
		<None Remove="appsettings.Production.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.Production.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Spectre.Console" Version="0.54.0" />
		<PackageReference Include="Spectre.Console.Cli" Version="0.53.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Modulos\Financeiro\LagFinanceApplication\LagFinanceApplication.csproj" />
		<ProjectReference Include="..\..\Utilitarios\LagControlUtil\LagControlUtil.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Resource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resource.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Resource.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resource.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
