//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagControlCLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagControlCLI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add transaction.
        /// </summary>
        internal static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        internal static string Diet {
            get {
                return ResourceManager.GetString("Diet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FigletFont_3d {
            get {
                object obj = ResourceManager.GetObject("FigletFont_3d", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        internal static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }

        internal static string NoTransactionsFound {
            get {
                return ResourceManager.GetString("NoTransactionsFound", resourceCulture);
            }
        }

        internal static string LoadingTransactions {
            get {
                return ResourceManager.GetString("LoadingTransactions", resourceCulture);
            }
        }

        internal static string ErrorLoadingTransactions {
            get {
                return ResourceManager.GetString("ErrorLoadingTransactions", resourceCulture);
            }
        }

        internal static string RetryPrompt {
            get {
                return ResourceManager.GetString("RetryPrompt", resourceCulture);
            }
        }

        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }

        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }

        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }

        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }

        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }

        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }

        internal static string IncomeLabel {
            get {
                return ResourceManager.GetString("IncomeLabel", resourceCulture);
            }
        }

        internal static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }

        internal static string TransferLabel {
            get {
                return ResourceManager.GetString("TransferLabel", resourceCulture);
            }
        }

        internal static string DataColumn {
            get {
                return ResourceManager.GetString("DataColumn", resourceCulture);
            }
        }

        internal static string ValueColumn {
            get {
                return ResourceManager.GetString("ValueColumn", resourceCulture);
            }
        }

        internal static string TypeColumn {
            get {
                return ResourceManager.GetString("TypeColumn", resourceCulture);
            }
        }

        internal static string AccountColumn {
            get {
                return ResourceManager.GetString("AccountColumn", resourceCulture);
            }
        }

        internal static string CategoryColumn {
            get {
                return ResourceManager.GetString("CategoryColumn", resourceCulture);
            }
        }

        internal static string NoPendingTransactions {
            get {
                return ResourceManager.GetString("NoPendingTransactions", resourceCulture);
            }
        }

        internal static string SelectPendingPrompt {
            get {
                return ResourceManager.GetString("SelectPendingPrompt", resourceCulture);
            }
        }

        internal static string ConfirmPendingQuestion {
            get {
                return ResourceManager.GetString("ConfirmPendingQuestion", resourceCulture);
            }
        }

        internal static string ConfirmingTransaction {
            get {
                return ResourceManager.GetString("ConfirmingTransaction", resourceCulture);
            }
        }

        internal static string TransactionConfirmed {
            get {
                return ResourceManager.GetString("TransactionConfirmed", resourceCulture);
            }
        }

        internal static string ErrorConfirmingTransaction {
            get {
                return ResourceManager.GetString("ErrorConfirmingTransaction", resourceCulture);
            }
        }

        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }

        internal static string PressEnterToReturn {
            get {
                return ResourceManager.GetString("PressEnterToReturn", resourceCulture);
            }
        }

        internal static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }

        internal static string SelectTransactionPrompt {
            get {
                return ResourceManager.GetString("SelectTransactionPrompt", resourceCulture);
            }
        }

        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }

        internal static string SelectModule {
            get {
                return ResourceManager.GetString("SelectModule", resourceCulture);
            }
        }

        internal static string LoadingAccounts {
            get {
                return ResourceManager.GetString("LoadingAccounts", resourceCulture);
            }
        }

        internal static string AccountDetailsHeader {
            get {
                return ResourceManager.GetString("AccountDetailsHeader", resourceCulture);
            }
        }

        internal static string PendingTotalIncome {
            get {
                return ResourceManager.GetString("PendingTotalIncome", resourceCulture);
            }
        }

        internal static string PendingTotalExpense {
            get {
                return ResourceManager.GetString("PendingTotalExpense", resourceCulture);
            }
        }

        internal static string PendingExpectedBalance {
            get {
                return ResourceManager.GetString("PendingExpectedBalance", resourceCulture);
            }
        }

        internal static string SelectCategoryPrompt {
            get {
                return ResourceManager.GetString("SelectCategoryPrompt", resourceCulture);
            }
        }

        internal static string SelectAccountPrompt {
            get {
                return ResourceManager.GetString("SelectAccountPrompt", resourceCulture);
            }
        }

        internal static string LoadingCategories {
            get {
                return ResourceManager.GetString("LoadingCategories", resourceCulture);
            }
        }

        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }

        internal static string ExpectedBalance {
            get {
                return ResourceManager.GetString("ExpectedBalance", resourceCulture);
            }
        }

        internal static string LastTransaction {
            get {
                return ResourceManager.GetString("LastTransaction", resourceCulture);
            }
        }

        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }

        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }

        internal static string InitialBalancePrompt {
            get {
                return ResourceManager.GetString("InitialBalancePrompt", resourceCulture);
            }
        }

        internal static string InitialBalanceValidation {
            get {
                return ResourceManager.GetString("InitialBalanceValidation", resourceCulture);
            }
        }

        internal static string BalanceAfter {
            get {
                return ResourceManager.GetString("BalanceAfter", resourceCulture);
            }
        }

        internal static string StartBalance {
            get {
                return ResourceManager.GetString("StartBalance", resourceCulture);
            }
        }

        internal static string EndBalance {
            get {
                return ResourceManager.GetString("EndBalance", resourceCulture);
            }
        }

        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }

        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }

        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }

        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }

        internal static string ValueLabel {
            get {
                return ResourceManager.GetString("ValueLabel", resourceCulture);
            }
        }

        internal static string TransferAccountLabel {
            get {
                return ResourceManager.GetString("TransferAccountLabel", resourceCulture);
            }
        }

        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        internal static string RangeConnector {
            get {
                return ResourceManager.GetString("RangeConnector", resourceCulture);
            }
        }

        internal static string DateStartPrompt {
            get {
                return ResourceManager.GetString("DateStartPrompt", resourceCulture);
            }
        }

        internal static string DateEndPrompt {
            get {
                return ResourceManager.GetString("DateEndPrompt", resourceCulture);
            }
        }

        internal static string DateInvalidFormat {
            get {
                return ResourceManager.GetString("DateInvalidFormat", resourceCulture);
            }
        }

        internal static string AccountLabel {
            get {
                return ResourceManager.GetString("AccountLabel", resourceCulture);
            }
        }

        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }

        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
    }
}
